import "./es6/1-basic-syntax/1-let-const";
// import './es6/1-basic-syntax/2-destructuring';
// import './es6/2-build-in-types/string';
// import './es6/2-build-in-types/array';
// import './es6/2-build-in-types/function';
// import './es6/2-build-in-types/object';
// import './es6/3-data-structure/lodash-example';
// import "./es6/4-module/import";
// import './es6/class-extends';
// import './es6/proxy-reflect';
// import "./es6/7-Proxy-Reflect/Proxy-Reflect";
// import "./es6/8-Promise/Promise";
// import './es6/4-iterator';
// import './es6/symbol';
// import './es6/module/ui';
// import './es6/generator-1';
// import './es6/weakset';
// import './es8/generator-2-async-await';
